### ISSUE TITLE
Can my account get blocked?

### ISSUE THREAD

**Issue by bruno-** [SebastianJ/revolut-api#2]
Hi,

thank you for making this library 🙏 I have read the readme and the interface looks amazing ✨ 

I have one concern tho: is it possible my Revolut account gets blocked by using their non-public API?
This reddit thread scared me https://www.reddit.com/r/Revolut/comments/d7swp3/account_blocked_for_suspicious_activity_postive/ As I rely on Revolut quite a bit, I wouldn't like the same happen here...

**Comment by mw911** [comment]
I am using the library for many months and my account got never blocked. Might also depend on how often you intend to use it

**Comment by bruno-** [comment]
Thanks
